name: Create Release from Example Vault

on:
  push:
    tags: ["*"]

env:
  REPO_NAME: ${{ github.event.repository.name }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  contents: write

#───────────────────────────────────────────────────────────────────────────────

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create Zip File
        id: create-zip
        run: |
          mkdir "${{ env.REPO_NAME }}"
          cp -r "Data" "Codes" "Extractions" "README.md" "Analysis" ".obsidian" "${{ env.REPO_NAME }}"
          zip -r "${{ env.REPO_NAME }}.zip" "${{ env.REPO_NAME }}"

      # DOCS https://github.com/softprops/action-gh-release?tab=readme-ov-file#%EF%B8%8F-uploading-release-assets
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ env.GITHUB_TOKEN }}
          files: ${{ env.REPO_NAME }}.zip
